### ISSUE TITLE
Project_Completed_Carson_Sheng_Weifeng

### ISSUE THREAD

**Issue by cahoffman** [UWMadison-computingtools/project1-avengers#1]
@cecileane
UWMadison-computingtools/project1-avengers@1d7bac1

Hello Cecil,
We have completed our project by following all the detailed instructions on the course website. If you have any questions let us know. Thanks.
-Carson, Sheng, Weifeng

**Comment by anyezijue49** [comment]
@cecileane I have add some necessary information into the  [main readme file](https://github.com/UWMadison-computingtools/project1-avengers/blob/master/README.md) make it easier to check. Thanks

**Comment by rebeccapost** [comment]
Hi team avengers! Below are my comments on your project, divided by step:

Overall Readme:
I like the setup of the readme, which headers for each steps and a part for discrepencies and examples to make sure everything is going correctly.

Step1:
-The check file was a great idea, to make sure that everything downloaded correctly.
-I think your file looks efficient, and I liked your use of $0 and grep to get the names for the URLs.
-I think you might have been able to skip the for loop that reads through web.txt using the --input-file option in wget.

Step2:
-I like that you created a size file to choose which are the smallest chromosomes.

Step3:
-I thought it was great that you created a discrepancy file to ensure the genomes are correct. I think you could have combined the combine.sh file and the get_discrepancy.sh file, and thus avoided creating the tnew files.
-It might have been better to check for discrepancies before you finish the file, just in case there are issues so you do not have to rerun the steps.
You could do this by having an if statement before you alter the genome in step 3 that compares v2 (as you called it) with the ref genome nucleotide like you do in get_discrepancy.sh.
-I thought that this was cool because you wrote the step in the shell. While very similar, I chose to do this in python.

Step4/5:
-I thought it was clever that you built in the number of blocks you wanted to produce.
-It would be nice for the smaller chromosomes to just be able to run the whole chromosome without figuring out how many blocks that means I need to put in the input. Perhaps you could have added a line that calculates the number of blocks possible for the chromosome, and use that as the default.
-I thought it was smart to have the catch for RAxML, and then install if it doesn't.

Step6:
-This step was well-written
-Just a difference between our groups:I thought it was interesting that you created the adjacent tree files in this step. My group subsetted the files in R instead.

Step7:
-The markdown file looks very clean. Because of the repetitive nature of the calls, you could have created a graph.chr() function that takes in the dataset and then creates the graphics, but the way you did it was excellent. The graphics with ggplot2 look great.

Overall, your documentation was excellent, both within files and in the readmes. I liked that you made the directories step numbers, but the names of the files are specific to what you are doing in the file. My group personally had trouble with unifying this, and I thought this was a great idea.
I thought you guys did a great job with the project, and I hope my comments help your future coding endeavors!

-Rebecca

**Comment by IcecreamWine** [comment]
Hi Sheng, Carson and Weifeng,

First of all, I really appreciate your excellent work and neat results. I git clone your repository and run your code. Nice job!

The main repository and sub-directories you use to organize your work are really neat and nicely organized. It's pretty clear that you separate steps of this project and put scripts and readme file of each step in the corresponding sub-directory named `step_*` and list all 7 steps in `scripts`. Nicely done! Besides the documentation in `document` is quite clear and useful for the new user for this project.

Your main readme file gives introductions to your repository which is really organized. But it's kind of minimal, it would be great if you add more sections such as `Pipeline overview` which make your work highly recognizable. I found one useful template [here](https://github.com/nstenz/TICR). And the readme files for the specific step are really helpful. It's pretty helpful that you give us the instructions of how to run the script and the results of this script. And the details of the script and examples are also useful. But I think it would be great if you could point out working directory for each script in the corresponding readme file.

I also appreciate the specific and clear comments inside code which makes me understand easily. Pretty helpful! The code are creative and neat which shows that you have a really great practice of shell. In step 3, it's precise that you also check if any discrepancy exists between the reference genome and reference nucleotides. Great thoughts! As for using RAxML, I think it would be better if you document the program RAxML not only its version in the readme file since it may be difficult for the new user for this project and it's easy to review later. And step 7 is pretty excellent visualization and nice summarization of your work. I really like the plots you made. Our group have the similar results and also used R markdown. It's just a tiny problem in the `RAxML_results`, I think there may be one unnecessary file named `chr2_all_trees`...

I also appreciate that you document the operating system since time consuming can be different due to the different system. Since in our group, Linux is almost three times faster than Mac OS or Stat server.

Overall, great job! You guys complete the whole steps of this project creatively and excellently and the documentations are also clear and helpful.

Cheers.
Yijing

**Comment by anqis929** [comment]
Hi team avengers! 

Great Work! Thanks for sharing all the codes and scripts! They are logically written and displayed.
I especially like that you have a readme file for each step to briefly introduce what you will do for this step.  Below are my couple comments on your work

Step 1:  I really liked that you checked if you have downloaded all the files in the website using 
if/else.  I also liked that you used “awk” in your command to catch the file size. 
Your logic is very clear how you first extract all the information on the website and the special web links you need to download the data. 

2. Step 2:  For step 2, I believe most of us used the similar method as step 1 to get the data.  If I understood correctly you saved the file size in the ***size_of_TAIRfiles.txt*** file. If you could add this text file it would be really useful for the readers new to this project. 

3. Step 3 : For step 3, our group used Python scripts, it’s great to see that other team uses shell scripts and still serve the purpose. I especially like how you saved everything that you are going to use in the next steps. 
 
4. step 4&5:  I think it was clever to have the number of blocks you wanted.  But I personally thin it would be easier for us to just have the number of blocks ready/calculated to type in the input for smaller chromosomes.

5. step 6/7 : you saved all the variables you are going to use in the loop before hand is great, so that you don't need to change the code of the loop if there is any mistake made in the variables. Also, if the two readMe files could be combined then it would be easier for us to read.  

Additionally, you could use python to reduce the workload, for example, in the last part of your code, you don't have to extract the adjacent blocks using shell scripts, and python could list out all of them which include the adjacent ones. 

I like it that you used “sed” a lot in your script. “sed” is a very powerful tool, but in some places trying grep is also a good idea. Also, using more pipelines than the arrows would be easier to read as well. 

In addition, The graph in ggplot looks great! 
But in general this step is excellent and serve the purpose! 

Last couple things: 
I like that you have a readme file for each step to briefly introduce what you will do for this step.  
But according to your README file on the first page, there should be three folders, scripts, document and RaxML_result, but actually only one directory exists, only the script folder is listed. Thus if the ReadMe file could be more precise and detailed, then it would be great.  

And for each script, you denoted that assume you are at the working directory, however, for me to run the script, I have to change the working directory constantly by myself, and in some scripts if I don’t change it the script will not run successfully.  Thus if you could add couple more codes at the beginning or the end of the each script to change working directory it would be so much easier for others to run your code. 

Again, excellent work and thank you for sharing. 
Happy holidays! 
Irene
